[package]

name = "client-rs"
version = "0.0.0"
authors = ["Aleksander Usov <aleksander.usov@gmail.com>"]

[dependencies]
#rustc-serialize = "0.3.12"
rustc-serialize = "*"
byteorder = "*"
openssl = "*"
#mio = "*"
#bytes = "*"
#nix = "*"
flate2 = "*"

#[dependencies.openssl]
#openssl = "0.5.5"
#git = "git://github.com/sfackler/rust-openssl"

[dependencies.mio]
#git = "https://github.com/AngryLawyer/rust-sdl2"
#mio = "0.3.0"
git = "https://github.com/carllerche/mio"
#git = "https://github.com/fhartwig/mio.git"

#git = "https://github.com/aleksander/mio.git"
#branch = "fixups"
