[package]

name = "client-rs"
version = "0.0.1"
authors = ["Aleksander Usov <aleksander.usov@gmail.com>"]

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl"

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs"

